/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { V2 } from "./V2";
export * as factories from "./factories";
export { V2__factory } from "./factories/V2__factory";
